name: vhbb
dependencies:
  - python=3.8
  - matplotlib
  - pip
  - ipykernel
  - pip:
    - numpy
    - h5py
    - scipy==1.5.4
    - mplhep
    - jupyter
    - uproot4==4.0.0
    - awkward==1.2.0
    - coffea==0.7.2
    - hist[plot]